services:
  - type: web
    name: attendance-scraper
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
